Areas/Admin/Controllers/OrganizationController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using VisitorWebsite.Areas.Admin.Models;

namespace VisitorWebsite.Areas.Admin.Controllers
{
    [Area("Admin")]
    [CheckAccess]
    public class OrganizationController : Controller
    {
        Uri baseAddress = new Uri("http://localhost:5153/api");
        HttpClient _client;

        public OrganizationController()
        {
            _client = new HttpClient();
            _client.BaseAddress = baseAddress;
        }
        public IActionResult GetOrganization()
        {
            List<OrganizationModel> organizations = new List<OrganizationModel>();
            HttpResponseMessage response = _client.GetAsync($"{_client.BaseAddress}/Organization").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                organizations = JsonConvert.DeserializeObject<List<OrganizationModel>>(data);
            }
            return View("OrganizationList", organizations);
        }
        public async Task<IActionResult> OrganizationForm(int? organizationID)
        {
            if (organizationID.HasValue)
            {
                var response = await _client.GetAsync($"{_client.BaseAddress}/Organization/{organizationID}");
                if (response.IsSuccessStatusCode)
                {
                    var data = await response.Content.ReadAsStringAsync();
                    var organization = JsonConvert.DeserializeObject<OrganizationModel>(data);
                    return View(organization);
                }
            }
            return View(new OrganizationModel());
        }

        [HttpPost]
        public async Task<IActionResult> Save(OrganizationModel model)
        {
            if (model.EstablishedDate == DateTime.MinValue)
            {
                model.EstablishedDate = DateTime.Now;
            }

            if (ModelState.IsValid)
            {
                var json = JsonConvert.SerializeObject(model);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                HttpResponseMessage response;

                if (model.OrganizationID == 0)
                    response = await _client.PostAsync($"{_client.BaseAddress}/Organization", content);
                else
                    response = await _client.PutAsync($"{_client.BaseAddress}/Organization/{model.OrganizationID}", content);

                if (response.IsSuccessStatusCode)
                    return RedirectToAction("GetOrganization");
            }
            return View("OrganizationForm", model);
        }

    }
}

Areas/Admin/Views/Organization/OrganizationForm.cshtml
@model VisitorWebsite.Areas.Admin.Models.OrganizationModel

<div class="container">
          <div class="page-inner">
            <div class="row">
              <div class="col-md-12">
              
                <div class="card" style="border:1px solid #2b3643;">
                    <form method="post" asp-controller="Organization" asp-action="Save">
                  <div class="card-header">
                     <div class="card-title">Organization Form</div>
                  </div>
                  <div class="card-body p-3">
                      @if (!ViewData.ModelState.IsValid)
                    {
                        <div asp-validation-summary="All" class="alert alert-danger" role="alert"></div>
                    }

                        <input type="text" value="@Model.OrganizationID" asp-for="OrganizationID" />
                    <div class="row">
                      <div class="col">
                        <div class="form-group">
                          <label asp-for="OrganizationName">Organization Name</label>
                          <input asp-for="OrganizationName"
                            type="text"
                            class="form-control" />
                          <span asp-validation-for="OrganizationName" class="text-danger"></span>
                        </div>
                      </div>

                        <div class="col">
                            <div class="form-group">
                                <label asp-for="Head">Head Name</label>
                                <input type="text"
                                        class="form-control" asp-for="Head"/>
                                <span asp-validation-for="Head" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <div class="row">
                                <div class="form-group">
                                    <label asp-for="City">City Name</label>
                                    <input type="text"
                                            class="form-control" asp-for="City"/>
                                        <span asp-validation-for="City" class="text-danger"></span>

                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <label asp-for="EstablishedDate">Established date</label>
                                    <input type="cal"
                                            class="form-control" asp-for="EstablishedDate" />
                                    <span asp-validation-for="EstablishedDate" class="text-danger"></span>

                                </div>
                            </div>
                        </div>

                        <div class="col">
                            <div class="form-group">
                                <label asp-for="Address">Address</label>
                                <textarea
                                        class="form-control" rows="5" asp-for="Address"></textarea>
                                    <span asp-validation-for="Address" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                  </div>
                  <div class="card-action">
                        <button class="btn btn-success" type="submit">Submit</button>
                        <a class="btn btn-danger" asp-controller="Organization" asp-action="GetOrganization">Cancel</a>
                  </div>
                    </form>
                </div>
              </div>
            </div>
          </div>
        </div>

@section Scripts {
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>
}

Areas/Admin/Views/Organization/OrganizationList.cshtml
@model List<VisitorWebsite.Areas.Admin.Models.OrganizationModel>

<div class="container">
    <div class="page-inner">
        <div class="row">
            <div class="col-md-12">
                <div class="card" style="border:1px solid #2b3643;">
                    <div class="card-header">
                        <div class="d-flex align-items-center">
                            <h4 class="card-title">Organizations</h4>
                            <a class="btn btn-primary btn-round ms-auto"
                            asp-area="Admin"
                               asp-controller="Organization" asp-action="OrganizationForm">
                                <i class="fa fa-plus"></i>
                                Add Organization
                            </a>
                        </div>
                    </div>
                    <div class="card-body">

                        <div class="table-responsive">
                            <table id="add-row"
                                   class="display table table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Head</th>
                                        <th>City</th>
                                        <th>Office</th>
                                        <th class="text-center">Receptionist count</th>
                                        <th>Established date</th>
                                        <th style="width: 10%" class="text-center">Actions</th>
                                    </tr>
                                </thead>
                                
                                <tbody>
                                    
                                    @foreach (var v in Model)
                                    {
                                        <tr>
                                            <td>@v.OrganizationName</td>
                                            <td>@v.Head</td>
                                            <td>@v.City</td>
                                            <td>@v.Address</td>
                                            <td class ="text-center"><a class="btn btn-outline-success" asp-area="Admin" asp-controller="User" asp-action="GetReceptionists" asp-route-organizationID="@v.OrganizationID">@v.ReceptionistCount</a></td>

                                            <td>@v.EstablishedDate.ToString("dd/MM/yyyy") <br/> @v.EstablishedDate.ToString("hh:mm tt")</td>

                                            <td class="text-center">
                                                <div class="form-button-action">
                                                    <a asp-controller="Organization" asp-action="OrganizationForm" asp-route-organizationID="@v.OrganizationID"
                                                            class="btn btn-link btn-warning btn-lg" >
                                                        <i class="fa fa-edit"></i>
                                                    </a>
                                                    <a data-id="@v.OrganizationID"
                                                       class="btn btn-link btn-danger btn-lg"
                                                       id="deleteRecord">
                                                        <i class="fa fa-times"></i>
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                    }
                                  
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
     <script>
         $(document).ready(function () {

             // Add Row
             $("#add-row").DataTable({
                 pageLength: 5,
             });

            $(document).on('click', '#deleteRecord', function () {
               const id = $(this).data('id'); //Retrieve the ID from the button's data-id attribute
               console.log('ID ============= ' + id);

               Swal.fire({
                   title: 'Are you sure?',
                   text: "This action cannot be undone!",
                   icon: 'warning',
                   showCancelButton: true,
                   confirmButtonColor: '#3085d6',
                   cancelButtonColor: '#d33',
                   confirmButtonText: 'Yes, delete it!'
               }).then((result) => {
                   if (result.isConfirmed) {
                       $.ajax({
                         url: `http://localhost:5153/api/Organization/${id}`,
                           type: 'DELETE',
                           success: function (response) {
                               Swal.fire(
                                   'Deleted!',
                                   'The record has been deleted.',
                                   'success'
                               ).then(() => {
                                   location.reload();
                               });
                           },
                           error: function (xhr, status, error) {
                               console.log('Error ============ ' + error);
                               Swal.fire(
                                   'Error!',
                                   'Failed to delete the record.',
                                   'error'
                               );
                           }
                       });
                   }
               });
           });

         });
        
     </script>

    <script>
        
    </script>

}